version: "3.5"

services:
  postgres-db:
    container_name: porter_management_pg_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=porter_management_db

  mongodb:
    container_name: porter_management_mongo_db
    image: bitnami/mongodb:5.0
    networks:
      - default
    environment:
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: "123456"
    ports:
      - '27017:27017'

  mongodb-ui:
    container_name: mongodb-ui
    image: mongo-express:0.54
    restart: always
    depends_on:
      - mongodb
    networks:
      - default
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: "123456"
    ports:
      - '8081:8081'

networks:
  default:
    name: MyNetwork
