version: "3.5"

services:
  postgres-db:
    container_name: porter_management_db
    image: postgres:16
    restart: always
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=porter_management_db

  mongodb:
    container_name: porter_management_mongo_db
    image: bitnami/mongodb:5.0
    restart: always
    networks:
      - default
    environment:
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: "123456"
    ports:
      - '27017:27017'

  mongodb-ui:
    container_name: mongodb-ui
    image: mongo-express:0.54
    restart: always
    depends_on:
      - mongodb
    networks:
      - default
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: "123456"
    ports:
      - '8081:8081'

  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    restart: always
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - default

  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    container_name: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - '9092:9092'
    networks:
      - default
    depends_on:
      - zookeeper

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    container_name: kowl
    restart: always
    hostname: kowl
    volumes:
      - ./kowl.yml:/etc/kowl/config.yaml
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    ports:
      - "8082:8080"
    networks:
      - default
    depends_on:
      - kafka

networks:
  default:
    name: MyNetwork
